name: my_hr_system
description: "DataHub AI HR system."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.0.0
  file_picker: ^11.0.2
  get: ^4.7.3
  google_fonts: ^8.0.2
  http: ^1.5.0
  pdf: ^3.11.3
  printing: ^5.14.3
  shared_preferences: ^2.3.3
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
